# Generated by Django 4.2.11 on 2024-05-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='product',
        ),
    ]
