# Generated by Django 4.2.11 on 2024-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_attribute_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
