# Generated by Django 4.2.11 on 2024-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_value_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='admin_name',
            field=models.CharField(default='attribute name at admin page', max_length=50),
        ),
    ]
