# Generated by Django 4.2.11 on 2024-05-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_attribute_admin_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='admin_name',
            new_name='name_for_admin_page',
        ),
    ]
