# Generated by Django 4.2.11 on 2024-05-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_admin_name_attribute_name_for_admin_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='name_for_admin_page',
            field=models.CharField(default='product value at admin page', max_length=150),
        ),
    ]
