# Generated by Django 4.2.11 on 2024-05-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_value_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='name_for_admin_page',
        ),
        migrations.RemoveField(
            model_name='value',
            name='name_for_admin_page',
        ),
    ]
