# Generated by Django 4.2.11 on 2024-05-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_attribute_name_for_admin_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_on_shop_page',
            field=models.ImageField(null=True, upload_to='static/assets/images/shop/'),
        ),
    ]
