# Generated by Django 4.2.11 on 2024-05-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_image_on_shop_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
