# Generated by Django 4.2.11 on 2024-05-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='desc',
            field=models.CharField(default='Describe your category', max_length=100),
        ),
    ]
