# Generated by Django 4.2.11 on 2024-05-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_categories_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
