# Generated by Django 4.2.11 on 2024-05-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static/assets/images/about/'),
        ),
    ]
