name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.2]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest and generate HTML report
      run: |
        pytest --html=pytest_report.html  # Generate HTML report
        flake8 --format=html --htmldir=flake8-report
    - name: Upload pytest HTML report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pytest-html-report
        path: pytest_report.html
    - name: Upload flake8 HTML report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: flake8-html-report
        path: flake8-report
